
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eks-test-secret
spec:
  provider: aws
  secretObjects:
  - secretName: test-secret-latest
    type: Opaque
    data: 
    - objectName: username 
      key: username
    - objectName: password 
      key: password
  parameters:
    objects: |
        - objectName: "test-secret"
          objectType: "secretsmanager"
          jmesPath:
            - path: "username"
              objectAlias: "username"            
            - path: "password"
              objectAlias: "password"
