deployment:
   name: mavenwebappdeployment
replicaCount: 1
label: mavenwebapp
image:
  repository: kuppamdocker/maven-web-application
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: mavenwebappsvc
  port: 80
  targetPort: 8080
  type: LoadBalancer
