- hosts: appServers
  become: true
  tasks:
  #- name: Install lxml
   # pip: name=lxml
  - name: remove war file from temp folder
    shell: rm -rf /tmp/maven-web-application.war
  - name: "Download war file"
    maven_artifact:
      group_id: com.mt
      artifact_id: maven-web-application
      extension: war
      version: pomversion
      repository_url: "http://54.77.243.106:8081/repository/Snapshot_Repository/" 
      username: admin
      password: H@rshihari03
      dest: "/tmp/maven-web-application.war"
      mode: '0644'
  - name: Copy the war file
    copy:
      src: /tmp/maven-web-application.war
      dest: /opt/tomcat9/webapps/
      remote_src: yes
  - name: Stop tomcat services
    shell: /opt/tomcat9/bin/shutdown.sh

  - name: Start Tomcat
    shell: nohup /opt/tomcat9//bin/startup.sh
