- hosts: appServers
  become: true
  tasks:
   - name: Download an  artifact from Nexus repo
     nexus:
        nexus_endpoint: "http://34.251.138.104:8081/repository/"
        username: "admin"
        password: "H@rshihari03"
        artifact_id: "maven-web-application"
        artifact_format: "war"
        target: "/tmp/maven-web-application-1.0.0.war"
        repository: "Release_Repository"
      ignore_errors: true
   - name: copy war file to webapps
     copy: 
       src: "/tmp/maven-web-application-1.0.0.war"
       dest: "/opt/tomcat9/webapps/maven-web-application.war"
       mode: 0777
       remote_src: yes
