- hosts: appServers
  become: true
  tasks:
  - name: Downloading artifacts from Nexus server
    get_url: 
      url: http://34.251.138.104:8081/repository/Snapshot_Repository/
      #url: http://34.251.138.104:8081/repository/Snapshot_Repository/com/mt/maven-web-application/0.0.1-SNAPSHOT/*.war
      dest: /opt/tomcat9/webapps/
      mode: 0755
      url_username: "{{admin_username}}"
      url_password: "{{admin_password}}"
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    ansible.builtin.file:
        path: /etc/foo.conf
        state: touch
        mode: u=rw,g=r,o=r

  #- name: Deploying war file to tomcat
   # copy: 
    #  src: target/maven-web-application.war
     # dest: /opt/tomcat9/webapps
      
