- hosts: appServers
  become: true
  tasks:
  - name: Downloading artifacts from jfrog server
    get_url: 
      url: http://52.214.25.21:8081/artifactory/result/
      dest: /opt/tomcat9/webapps
      mode: 0755
  #- name: Deploying war file to tomcat
   # copy: 
    #  src: target/maven-web-application.war
     # dest: /opt/tomcat9/webapps
      
