---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:       # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
  - data:
  - key: username      # data field to populate
    objectName: ACSPSecrets   # name of the mounted content to sync. this could be the object name or the object alias 
  secretName: ACSPEKSSecret     # name of the Kubernetes Secret object
  type: Opaque         # type of the Kubernetes Secret object e.g. Opaque, kubernetes.io/tls

  parameters:
    objects: |
      - objectName: "MySecret2"
        objectType: secretsmanager
        objectAlias: secret-token
