---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: creds1
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: creds1
    type: Opaque
    data:
    - objectName: "Mypassword"
      key: password
  parameters:
      objects: |
         - objectName: arn:aws:secretsmanager:eu-west-1:350295275362:secret:creds1-PiI68s
           objectAlias: "MyPassword"

      #objects: |
       # - objectName: "creds1"
        #  objectType: "secretsmanager"
         # jmesPath:
          #  - path: "password"
           #   objectAlias: "Mypassword"
  


