---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: test-secret
      type: Opaque
      data:
        - objectName: "username"
          key: username
        - objectName: "password"
          key: password
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:eu-west-1:350295275362:secret:test-secret-kuhwxc
        jmesPath:
            - path: "username"
              objectAlias: "username"            
            - path: "password"
              objectAlias: "password"

