---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: creds
      type: Opaque
      data:
        - objectName: "MySecretPassword"
          key: password
        - objectName: "MySecretUsername"
          key: username
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:eu-west-1:350295275362:secret:creds-cUmK8S
        jmesPath:
            - path: "username"
              objectAlias: "MySecretUsername"
            - path: "password"
              objectAlias: "MySecretPassword"
    #objects: |
     # - objectName: arn:aws:secretsmanager:eu-west-1:350295275362:secret:creds-cUmK8S
      #  objectAlias: "MySecretPassword"
