---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
  - secretName: api-token-test
    type: Opaque
    data: 
    - objectName: secret-token
      key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: prod/service/test-token
        objectType: secretsmanager
        objectAlias: secret-token
