---
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  secretObjects:
    - secretName: creds1
      type: Opaque
      data:
        - objectName: "MySecretPassword"
          key: password
  parameters:
    objects: |
       - objectName: arn:aws:secretsmanager:eu-west-1:350295275362:secret:creds1-PiI68s
         objectAlias: "MySecretPassword"
  


