apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
  annotations:
     secret.reloader.stakater.com/reload: "test-secret-latest"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: mavenwebapppod
      labels:
        app: mavenwebapp
    spec:
      serviceAccountName: mavenwebapp
      containers:
      - name: mavenwebappcontainer
        image: kuppamdocker/maven-web-application:#pomversion
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        env:
        - name: username
          valueFrom:
            secretKeyRef:
              name: test-secret-latest
              key: username
        - name: password
          valueFrom:
            secretKeyRef:
              name: test-secret-latest
              key: password
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "eks-test-secret"
           
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
    app: mavenwebapp
  ports:
  - port: 80
    targetPort: 8080
