apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: eks-test-secret
spec:
  provider: aws
  secretObjects:
  - secretName: test-secret-new
    type: Opaque
    data:
    - objectName: username
      key: username
    - objectName: password
      key: password
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:eu-west-1:350295275362:secret:test-secret-new-O0AOgR"
          jmesPath:
            - path: "username"
              objectAlias: "username"
            - path: "password"
              objectAlias: "password"
